# Generated by Django 5.0.4 on 2025-01-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(blank=True, default='user', max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('plate_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('oil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.oiltype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('oil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.oiltype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.station')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('maintainer', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.station')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('oil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.oiltype')),
            ],
        ),
    ]
