# Generated by Django 5.1.5 on 2025-01-26 09:03

import dispensing_operations_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing_operations_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='status',
            new_name='Method',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='date',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.CharField(default=dispensing_operations_app.models.get_default_datetime, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='Time',
            field=models.TimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='created_at',
            field=models.CharField(default=dispensing_operations_app.models.get_default_datetime, max_length=20),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='report',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oiltype',
            name='price',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.CharField(default=dispensing_operations_app.models.get_default_datetime, max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.CharField(default=dispensing_operations_app.models.get_default_datetime, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.CharField(default=dispensing_operations_app.models.get_default_datetime, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.station'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='oiltype',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='station',
            name='created_at',
            field=models.CharField(default=dispensing_operations_app.models.get_default_datetime, max_length=20),
        ),
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(max_length=200)),
                ('Time', models.TimeField(blank=True, max_length=30, null=True)),
                ('report', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.station')),
            ],
        ),
    ]
