# Generated by Django 5.1.5 on 2025-01-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing_operations_app', '0002_rename_status_customer_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='Calibration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.calibration'),
            preserve_default=False,
        ),
    ]
