# Generated by Django 5.1.5 on 2025-01-26 11:55

import dispensing_operations_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing_operations_app', '0003_maintenance_calibration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='oil_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='plate_number',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('plate_number', models.CharField(max_length=50, null=True)),
                ('created_at', models.CharField(default=dispensing_operations_app.models.get_default_datetime, max_length=20)),
                ('Method', models.CharField(max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='customer_files/')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.customer')),
                ('oil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.oiltype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.user')),
            ],
        ),
    ]
