# Generated by Django 5.1.5 on 2025-01-16 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing_operations_app', '0003_oiltype_price_alter_maintenance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.station'),
            preserve_default=False,
        ),
    ]
