# Generated by Django 5.1.5 on 2025-01-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing_operations_app', '0004_remove_customer_oil_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
