# Generated by Django 5.1.5 on 2025-01-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing_operations_app', '0004_user_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispensing_operations_app.station'),
        ),
    ]
