# Generated by Django 5.1.5 on 2025-01-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing_operations_app', '0005_alter_customerdetail_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Method',
        ),
        migrations.AddField(
            model_name='customer',
            name='Phonenumber',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
