# Generated by Django 5.1.5 on 2025-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing_operations_app', '0006_remove_customer_method_customer_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='status',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
