# Generated by Django 5.1.5 on 2025-01-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing_operations_app', '0009_alter_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
