# Generated by Django 5.1.5 on 2025-02-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing_operations_app', '0012_customerresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
