# Generated by Django 5.1.5 on 2025-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing_operations_app', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oil_type',
            field=models.CharField(max_length=50),
        ),
    ]
