# Generated by Django 5.1.5 on 2025-04-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing_operations_app', '0018_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintainer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
